//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaggingLibrary.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaggingLibrary.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object [abstract]
        ///animal :: object [abstract]
        ///mammal :: animal
        ///dog &amp; cat :: mammal
        ///dolphin :: whale
        ///whale :: mammal
        ///
        ///fur :: hair
        ///whiskers :: hair
        ///mammal -&gt; hair
        ///
        ///tail :: appendage
        ///appendage -&gt; animal
        ///
        ///dog ~&gt; tail
        ///dog -&gt; fur
        ///
        ///cat -&gt; tail
        ///cat -&gt; whiskers
        ///cat ~&gt; fur
        ///
        ///whale ~&gt; whiskers
        ///
        ///feline =&gt; cat
        ///canine =&gt; dog
        ///.
        /// </summary>
        internal static string Animals {
            get {
                return ResourceManager.GetString("Animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genre [abstract]
        ///instrument [abstract]
        ///string-instrument &amp; wind-instrument &amp; precussion-instrument &amp; electronic-instrument &amp; keyboard-instrument :: instrument [abstract]
        ///brass-instrument &amp; woodwind-instrument :: wind-instrument [abstract]
        ///reed-instrument :: woodwind-instrument [abstract]
        ///single-reed-instrument &amp; double-reed-instrument :: reed-instrument [abstract]
        ///slide-brass &amp; valved-brass :: brass-instrument [abstract]
        ///flute :: woodwind-instrument
        ///whistle &amp; gemshort &amp; flageolet &amp; recorder &amp; tonett [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
    }
}
