os: Visual Studio 2019
configuration: Release
install:
  - "SET PATH=C:\\ProgramData\\chocolatey\\bin;%PATH%"
  - choco install gitversion.portable -y --version 5.5.0
  - gitversion /l console /output buildserver
  - choco install GitReleaseNotes.Portable
  - choco install opencover.portable
  - choco install codecov
before_build:
  - nuget restore
  - GitReleaseNotes . /AllTags /C breaking /O ReleaseNotes.md || exit 0
build:
  project: TaggingLibrary.sln
test_script:
  - OpenCover.Console.exe -target:dotnet.exe -targetargs:"test --configuration %CONFIGURATION% --no-build" -register:user -filter:"+[*]* -[*.Tests]* -[xunit*]*" -output:coverage.xml -oldStyle
after_test:
  - codecov -f "coverage.xml"
artifacts:
  - path: 'ReleaseNotes.md'
  - path: '**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: 2tZ8tu75MkmhyIcFGzFZsukJx9WAfV94mMtIAnSlurGlGqKaUhG6n6fTimXiIQiB
  skip_symbols: false
  artifact: /.*\.nupkg/
skip_commits:
  files:
    - .gitattributes
    - .gitignore
    - CodeMaid.config
    - license.md
