// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("971b5482-a40f-48fc-99e2-26015146bc68")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("TaggingLibrary.Tests")]
